FROM phusion/baseimage:0.9.22
MAINTAINER Leland Later <llater@802secure.com>

RUN apt-get update -y && apt-get install -y wget
RUN wget -qO - https://openresty.org/package/pubkey.gpg | apt-key add -
RUN apt-get install -y software-properties-common && \
    add-apt-repository -y "deb http://openresty.org/package/ubuntu $(lsb_release -sc) main" && \
    apt-get update -y && \
    apt-get install -y openresty nginx

RUN mkdir -p /etc/my_init.d
COPY start_nginx.sh /etc/my_init.d/start_nginx.sh
RUN chmod +x /etc/my_init.d/start_nginx.sh

RUN mkdir /static

COPY nginx.conf /etc/nginx/nginx.conf
COPY webelk.nginx.conf conf/conf.d/webelk.nginx.conf # cert obtained

RUN curl -s https://api.github.com/repos/auth0/nginx-jwt/releases/latest | grep browser_download_url | cut -d '"' -f 4 | wget -qi -
RUN tar xf nginx-jwt.tar.gz

ENV PATH /usr/local/openresty/nginx/sbin:$PATH

RUN apt-get autoremove -y && \
    dpkg -l | awk '/^rc/ {print $2}' | xargs dpkg --purge && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

CMD ["/sbin/my_init"]
