FROM openresty/openresty:alpine
MAINTAINER 'Leland Later <lelandlater@gmail.com>'

RUN apk add --no-cache curl ca-certificates wget
RUN mkdir -p /data/letsencrypt /etc/letsencrypt /usr/local/openresty/nginx/static
COPY nginx.conf /usr/local/openresty/nginx/conf/nginx.conf
RUN rm /etc/nginx/conf.d/default.conf
COPY ssl.ataraxia.nginx.conf /etc/nginx/conf.d/
COPY proxy_params /etc/nginx/proxy_params
RUN rm -rf /usr/local/openresty/nginx/html/*
COPY html/ /usr/local/openresty/nginx/html
RUN curl -s https://api.github.com/repos/auth0/nginx-jwt/releases/latest | grep browser_download_url | cut -d '"' -f 4 | wget -qi -
RUN tar -xf nginx-jwt.tar.gz
