FROM openresty/openresty:alpine
MAINTAINER 'Leland Later'
COPY nginx.conf /usr/local/openresty/nginx/conf/nginx.conf
RUN rm /etc/nginx/conf.d/default.conf
COPY local.ataraxia.nginx.conf /etc/nginx/conf.d/
COPY proxy_params /etc/nginx/proxy_params
