#%RAML 1.0
---
title: Cue API
description: # Cue API ## Build shared playlists
version: v0
baseUri: https://api.cue.zone/{version}
protocols: [ HTTPS ]
documentation: https://docs.cue.zone/api
  - title: CueAPIReference
mediaType: application/json

/users:
  /{uid}:
    get:
    post:
    put:
    delete:

/events:
  /{evid}:
    get:
      description: An event's host, returned as UUID.
      queryParameters:
        host:
          displayName: Host
          description: A mapping of a Cue user UUID to a Spotify user URI as varchar.
          type: uuid
          example: ac85c9cb-e2bc-4879-895d-8885810e49d0
          required: false
        name:
          displayName: Event Name
          description: The name of the event, set by the host at creation.
          example: Blake House Party
          required: false
        cid:
          displayName: Cue ID
          description: Unique identifier for a Cue (one per event).
          type: uuid
          example: ac85c9cb-e2bc-4879-895d-8885810e49d0
          required: false

    


/cues:
  /{cid}:
    get:
    post:
    put:
    delete: