AWSTemplateFormatVersion: '2010-09-09'

Description: Host instance for Cue API.

Resources:

  CueServer:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-09d2fb69 # ubuntu 16.04 LTS ; hvm:ebs-ssd ; us-west-1 ## make AMIs for dev?
      InstanceType: t2.small
      KeyName: key0-cue-api
      NetworkInterfaces:
        -
          NetworkInterfaceId: !ImportValue CueNetworkInterfaceID

  CueData:
    Type: AWS::EC2::Volume
    Properties:
      AvailabilityZone: !GetAtt CueServer.AvailabilityZone
      Size: 8
    #DeletionPolicy: Snapshot

  AttachData:
    Type: AWS::EC2::VolumeAttachment
    Properties:
      Device: "/dev/sdh"
      InstanceId: !Ref CueServer
      VolumeId: !Ref CueData