version: '3.1'
services:
  gui:
    container_name: gui0
    restart: always
    build: ./gui
    expose:
      - 9000
    links:
      - api
    volumes:
      - static:/static
  api:
    container_name: api0
    restart: always
    build: ./api
    expose:
      - 10101
    links:
      - cassandra0:cassandra
      - redis
  cassandra0:
    image: cassandra
    container_name: cassandra0
    ports:
     - 9042:9042
     - 7199
  cassandra1:
    image: cassandra
    container_name: cassandra1
    ports:
     - 9142:9042
    links:
     - cassandra0:seed
    environment:
     - CASSANDRA_SEEDS=seed
  cassandra2:
    image: cassandra
    container_name: cassandra2
    ports:
     - 9242:9042
    links:
     - cassandra0:seed
    environment:
     - CASSANDRA_SEEDS=seed
  redis:
    image: redis:3.0-alpine
    command: redis-server --requirepass something-secret #devpassword
    ports:
      - 6379:6379
    volumes:
      - redis:/data
