version: '3.4'
services:
  app:
    container_name: app_1
    restart: always
    build: app
    ports:
      - 8000:8000
    environment:
      - VERSION="0.1"
  openresty:
    image: openresty/openresty:alpine
    ports:
      - 80:80
      - 443:443
  tests:
    build:
      context: app
      dockerfile: Dockerfile-tests

