version: '3.1'
services:
  gui:
    container_name: gui_0
    restart: always
    build: ./gui
    expose:
      - 9000
    links:
      - api
    volumes:
      - static:/static
  api:
    container_name: api_0
    restart: always
    build: ./api
    expose:
      - 10101
    links:
      - cassandra0:cassandra
  cassandra0:
    image: cassandra
    container_name: cassandra_0
    ports:
     - 9042:9042
     - 7199
  cassandra1:
    image: cassandra
    container_name: cassandra_1
    ports:
     - 9142:9042
    links:
     - cassandra0:seed
    environment:
     - CASSANDRA_SEEDS=seed
  cassandra2:
    image: cassandra
    container_name: cassandra_2
    ports:
     - 9242:9042
    links:
     - cassandra0:seed
    environment:
     - CASSANDRA_SEEDS=seed
volumes:
  static:
  #./data/cassandra:
  #  driver: rex-ray


