FROM golang:alpine AS build-env
MAINTAINER 'Leland Later <llater@ataraxia.io>'
ADD . /src
RUN echo http://mirror.yandex.ru/mirrors/alpine/v3.5/main > /etc/apk/repositories
RUN echo http://mirror.yandex.ru/mirrors/alpine/v3.5/community >> /etc/apk/repositories 
RUN apk update && apk add --no-cache git ca-certificates
RUN go get -u \
    github.com/sirupsen/logrus \
    github.com/gorilla/mux \
    github.com/stretchr/testify/suite \
    github.com/lib/pq
WORKDIR /src
ENTRYPOINT go test .
