version: '3.4'
services:
  app:
    container_name: app_0
    restart: always
    build: app
    ports:
      - 8000
    environment:
      - VERSION="0.1"
    labels:
      - io.ataraxia.app
      - io.ataraxia.app.VERSION=0.1
      - io.ataraxia.app.launched_at=
      - io.ataraxia.app.build_id= #{{ build_id }}
  #postgres:
  #  container_name: postgres_0
  #  restart: always
  #  build: ./postgres
  #  ports:
  #    - 5432:5432
  #  environment:
  #    - ATARAXIA_DB_USER=ataraxia
  #    - ATARAXIA_DB_PASSWORD=this-is-a-password
  #    - ATARAXIA_DB_DATABASE=ataraxiadb
  #    - POSTGRES_USER=postgres
  #    - POSTGRES_PASSWORD=this-is-a-password
  #  volumes:
  #    - pgdata:/var/lib/postgresql/data
  #  labels:
  #    - io.ataraxia.postgres
  #    - io.ataraxia.postgres.launched_at=
  #    - io.ataraxia.postgres.build_id=
  openresty-local:
    container_name: openresty_local_0
    links:
      - app
    build:
      context: ./openresty
      dockerfile: Dockerfile-local
    ports:
      - 80:80
      - 443:443
    environment:
      - JWT_SECRET=this-is-a-secret
  #openresty-acq:
  #  container_name: openresty_acq_0
  #  build:
  #    context: openresty
  #    dockerfile: Dockerfile-acq
  #  ports:
  #    - 80:80
  #    - 443:443
  #  environment:
  #    - JWT_SECRET="" 
  #  volumes:
  #    - certs:/etc/letsencrypt
  #    - certs_data:/data/letsencrypt
  #letsencrypt:
  #  container_name: letsencrypt_0
  #  image: deliverous/certbot
  #  volumes:
  #    - certs:/etc/letsencrypt
  #    - certs_data:/data/letsencrypt
  #openresty-ssl:
  #  container_name: openresty_ssl_0
  #  build:
  #    context: openresty
  #    dockerfile: Dockerfile-ssl
  #  ports:
  #    - 80:80
  #    - 443:443
  #  environment:
  #    - JWT_SECRET="this-is-a-secret"
  #  volumes:
  #    - certs:/etc/letsencrypt
  #    - certs_data:/data/letsencrypt
  #tests:
  #  container_name: tests
  #  build:
  #    context: app
  #    dockerfile: Dockerfile-tests
volumes:
  certs:
    driver: local
    name: ssl_certs
  certs_data:
    driver: local
    name: ssl_certs_data
  pgdata:
    driver: local
    name: pgdata
